// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchTimeBackEnd.Models;

#nullable disable

namespace SearchTimeBackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250210210219_Initialize-Database")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SearchTimeBackEnd.Models.SearchResultItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SearchResultItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "black",
                            Title = "Piano"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Title = "Video Game"
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            Title = "Beverage"
                        },
                        new
                        {
                            Id = 4,
                            Color = "purple",
                            Title = "Tunnel"
                        },
                        new
                        {
                            Id = 5,
                            Color = "purple",
                            Title = "Dress"
                        },
                        new
                        {
                            Id = 6,
                            Color = "purple",
                            Title = "Tunnel"
                        },
                        new
                        {
                            Id = 7,
                            Color = "purple",
                            Title = "Microorganism"
                        },
                        new
                        {
                            Id = 8,
                            Color = "purple",
                            Title = "Bench"
                        },
                        new
                        {
                            Id = 9,
                            Color = "purple",
                            Title = "Monster"
                        },
                        new
                        {
                            Id = 10,
                            Color = "purple",
                            Title = "Gi"
                        },
                        new
                        {
                            Id = 11,
                            Color = "blue",
                            Title = "Guitar"
                        },
                        new
                        {
                            Id = 12,
                            Color = "blue",
                            Title = "Ocean"
                        },
                        new
                        {
                            Id = 13,
                            Color = "blue",
                            Title = "Okra"
                        },
                        new
                        {
                            Id = 14,
                            Color = "blue",
                            Title = "Oscillation"
                        },
                        new
                        {
                            Id = 15,
                            Color = "blue",
                            Title = "Office"
                        },
                        new
                        {
                            Id = 16,
                            Color = "blue",
                            Title = "Octopus"
                        },
                        new
                        {
                            Id = 17,
                            Color = "blue",
                            Title = "Chipmunk"
                        },
                        new
                        {
                            Id = 18,
                            Color = "blue",
                            Title = "Tree"
                        },
                        new
                        {
                            Id = 19,
                            Color = "blue",
                            Title = "Ceiling"
                        },
                        new
                        {
                            Id = 20,
                            Color = "blue",
                            Title = "Eye"
                        },
                        new
                        {
                            Id = 21,
                            Color = "blue",
                            Title = "Toenail"
                        },
                        new
                        {
                            Id = 22,
                            Color = "red",
                            Title = "Dinosaur"
                        },
                        new
                        {
                            Id = 23,
                            Color = "red",
                            Title = "Planet"
                        },
                        new
                        {
                            Id = 24,
                            Color = "red",
                            Title = "Chapstick"
                        },
                        new
                        {
                            Id = 25,
                            Color = "red",
                            Title = "Food"
                        },
                        new
                        {
                            Id = 26,
                            Color = "red",
                            Title = "Lifeguard"
                        },
                        new
                        {
                            Id = 27,
                            Color = "red",
                            Title = "Tone"
                        },
                        new
                        {
                            Id = 28,
                            Color = "red",
                            Title = "Laptop"
                        },
                        new
                        {
                            Id = 29,
                            Color = "red",
                            Title = "Number"
                        },
                        new
                        {
                            Id = 30,
                            Color = "red",
                            Title = "Book"
                        },
                        new
                        {
                            Id = 31,
                            Color = "red",
                            Title = "Library"
                        },
                        new
                        {
                            Id = 32,
                            Color = "red",
                            Title = "Museum"
                        },
                        new
                        {
                            Id = 33,
                            Color = "red",
                            Title = "Star"
                        },
                        new
                        {
                            Id = 34,
                            Color = "red",
                            Title = "Inkling"
                        },
                        new
                        {
                            Id = 35,
                            Color = "red",
                            Title = "Beast"
                        },
                        new
                        {
                            Id = 36,
                            Color = "red",
                            Title = "Tenor"
                        },
                        new
                        {
                            Id = 37,
                            Color = "red",
                            Title = "Paperwork"
                        },
                        new
                        {
                            Id = 38,
                            Color = "red",
                            Title = "Ghoul"
                        },
                        new
                        {
                            Id = 39,
                            Color = "red",
                            Title = "Car"
                        },
                        new
                        {
                            Id = 40,
                            Color = "red",
                            Title = "Aircraft Carrier"
                        },
                        new
                        {
                            Id = 41,
                            Color = "red",
                            Title = "Balloon"
                        },
                        new
                        {
                            Id = 42,
                            Color = "red",
                            Title = "Party"
                        },
                        new
                        {
                            Id = 43,
                            Color = "red",
                            Title = "System"
                        },
                        new
                        {
                            Id = 44,
                            Color = "orange",
                            Title = "Orange"
                        },
                        new
                        {
                            Id = 45,
                            Color = "orange",
                            Title = "Nickelodeon"
                        },
                        new
                        {
                            Id = 46,
                            Color = "orange",
                            Title = "Sea"
                        },
                        new
                        {
                            Id = 47,
                            Color = "orange",
                            Title = "Sunset"
                        },
                        new
                        {
                            Id = 48,
                            Color = "orange",
                            Title = "Color"
                        },
                        new
                        {
                            Id = 49,
                            Color = "orange",
                            Title = "Computer"
                        },
                        new
                        {
                            Id = 50,
                            Color = "orange",
                            Title = "Floor"
                        },
                        new
                        {
                            Id = 51,
                            Color = "orange",
                            Title = "Chair"
                        },
                        new
                        {
                            Id = 52,
                            Color = "orange",
                            Title = "Chicken"
                        },
                        new
                        {
                            Id = 53,
                            Color = "orange",
                            Title = "Orangutan"
                        },
                        new
                        {
                            Id = 54,
                            Color = "orange",
                            Title = "Mohwak"
                        },
                        new
                        {
                            Id = 55,
                            Color = "orange",
                            Title = "Tissue"
                        },
                        new
                        {
                            Id = 56,
                            Color = "orange",
                            Title = "Skull"
                        },
                        new
                        {
                            Id = 57,
                            Color = "orange",
                            Title = "Basement"
                        },
                        new
                        {
                            Id = 58,
                            Color = "orange",
                            Title = "Nintendo"
                        },
                        new
                        {
                            Id = 59,
                            Color = "orange",
                            Title = "President"
                        },
                        new
                        {
                            Id = 60,
                            Color = "orange",
                            Title = "Stamp"
                        },
                        new
                        {
                            Id = 61,
                            Color = "orange",
                            Title = "Basketball"
                        },
                        new
                        {
                            Id = 62,
                            Color = "orange",
                            Title = "Flea"
                        },
                        new
                        {
                            Id = 63,
                            Color = "orange",
                            Title = "Spider"
                        },
                        new
                        {
                            Id = 64,
                            Color = "orange",
                            Title = "Tombstone"
                        },
                        new
                        {
                            Id = 65,
                            Color = "orange",
                            Title = "Fashion Statement"
                        },
                        new
                        {
                            Id = 66,
                            Color = "orange",
                            Title = "Sueprhero"
                        },
                        new
                        {
                            Id = 67,
                            Color = "orange",
                            Title = "Shoe"
                        },
                        new
                        {
                            Id = 68,
                            Color = "orange",
                            Title = "Puppet"
                        },
                        new
                        {
                            Id = 69,
                            Color = "orange",
                            Title = "Design"
                        },
                        new
                        {
                            Id = 70,
                            Color = "orange",
                            Title = "Crystal"
                        },
                        new
                        {
                            Id = 71,
                            Color = "orange",
                            Title = "Finger"
                        },
                        new
                        {
                            Id = 72,
                            Color = "orange",
                            Title = "Toe"
                        },
                        new
                        {
                            Id = 73,
                            Color = "orange",
                            Title = "Sweater"
                        },
                        new
                        {
                            Id = 74,
                            Color = "orange",
                            Title = "String"
                        },
                        new
                        {
                            Id = 75,
                            Color = "orange",
                            Title = "Fabric"
                        },
                        new
                        {
                            Id = 76,
                            Color = "orange",
                            Title = "Craft"
                        },
                        new
                        {
                            Id = 77,
                            Color = "orange",
                            Title = "Glow"
                        },
                        new
                        {
                            Id = 78,
                            Color = "orange",
                            Title = "Ear"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
