// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchTimeBackEnd.Models;

#nullable disable

namespace SearchTimeBackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250206214127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SearchTimeBackEnd.Models.SearchResultItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SearchResultItems");

                    b.HasData(
                        new
                        {
                            Id = 1167,
                            Color = "blue",
                            Title = "Guitar"
                        },
                        new
                        {
                            Id = 9992,
                            Color = "green",
                            Title = "Video Game"
                        },
                        new
                        {
                            Id = 2424,
                            Color = "red",
                            Title = "Dinosaur"
                        },
                        new
                        {
                            Id = 6552,
                            Color = "purple",
                            Title = "Dress"
                        },
                        new
                        {
                            Id = 7777,
                            Color = "red",
                            Title = "Planet"
                        },
                        new
                        {
                            Id = 1010,
                            Color = "orange",
                            Title = "President"
                        },
                        new
                        {
                            Id = 1011,
                            Color = "red",
                            Title = "Chapstick"
                        },
                        new
                        {
                            Id = 3360,
                            Color = "red",
                            Title = "Food"
                        },
                        new
                        {
                            Id = 1919,
                            Color = "green",
                            Title = "Beverage"
                        },
                        new
                        {
                            Id = 2123,
                            Color = "red",
                            Title = "Lifeguard"
                        },
                        new
                        {
                            Id = 6666,
                            Color = "purple",
                            Title = "Tunnel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
