
services:
 backend:
  container_name: search-time-back-end
  build:
   context: './SearchTimeBackEnd'
  ports:
   - "5000:5000"
  networks:
   - search-time-network
  depends_on:
   - db
  environment:
   - ASPNETCORE_URLS=http://+:5000
   - ConnectionStrings__DefaultConnection=Server=search-time-database-container,1433;Database=search-time-database;User Id=sa;Password=suchaS+r0ngp@ssword;TrustServerCertificate=True;
 db:
  container_name: search-time-database-container
  image: mcr.microsoft.com/mssql/server
  environment:
   ACCEPT_EULA: "Y"
   SA_PASSWORD: "suchaS+r0ngp@ssword"
   MSSQL_PID: "Developer"
  ports:
   - "1433:1433"
  networks:
   - search-time-network
  volumes:
   - sql_data:/var/opt/mssql
  healthcheck:
   test: ["CMD", "sqlcmd", "-U", "sa", "-P", "suchaS+r0ngp@ssword", "-Q", "SELECT 1"]
   interval: 30s
   retries: 5
   start_period: 30s
   timeout: 10s

networks:
 search-time-network:
  driver: bridge

volumes:
 sql_data:
